id: P30F48395
initial_creation_type: input
source_metadata:
  title: Sixteen Arhats
  language: fr
  description: 'A selection of texts related to the Sixteen Arhats or Sixteen Elders
    (ṣoḍaśa sthavirāḥ; Tib. gnas brtan bcu drug):'
  volume:
    f2c11bbbcd684cba8c0fe4c1209f71b2:
      title: A Brief Practice of Paying Homage and Making Offerings to the Sixteen
        Elders
      parent: Practices
    3d6b0145eabc4b0baa43cb159b1eb066:
      title: 'The Heart of Wish-Fulfilling Jewels: A Brief Practice for Paying Homage
        and Making Offerings to the Buddha together with his retinue of Arhats'
      parent: Practices
    50945968e25a4b66900f64a5a361e0c7:
      title: A Practice of Paying Homage and Making Offerings to the Sixteen Elders
      parent: Practices
    b4bcdb8972364912873d415b26fb7f5b:
      title: A Brief Practice for Paying Homage and Making Offerings to the Buddha
        together with his retinue of Arhats
      parent: Practices
    479d8d3bc6564ecaad5b5836301e53b1:
      title: Supplication to Lord Buddha together with the Sixteen Arhats
      parent: Prayers
created_at: '2022-03-01T05:51:16.715385'
last_modified_at: '2022-03-01T05:51:16.715388'
